spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hidden-method:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 810129
    username: root
    url: jdbc:mysql://localhost:3306/war_ships_fight?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      cache:
        period: 0
      static-locations: file:src/main/resources/static/
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8002
After 3 years of frustation here is a solution for a working HOT SWAP:


application.yaml:

